version: '3'
services:
  web:
    build: olab4
    container_name: olab4-developer
    ports:
      - 80:80
      - 443:443
      - 3306:3306
    volumes:
      - ./Data:/var/lib/mysql
      - ../../..:/var/www/vhosts
      - ./OLab4/apache/vhosts.d:/etc/httpd/vhosts.d
    restart: always
    extra_hosts:
      - "database:127.0.0.1"
      - "debugger:192.168.1.143"